[system]
addr=":8090"
mode="release"  #debug/release
static-path="static"


[postgres]
dsn = "host=distsys-postgres user=distsys password=admin dbname=distsys port=5432 sslmode=disable TimeZone=Asia/Shanghai"
max-idle-conns=10
max-open-conns=100
log-mode=""
log-zap=false
encry-code="088idq93wz4n1rlqvpwrpc7baadryqm6"

[zap]
level="error"
format="console"
prefix="[distsys]"
director="log"
showLine=true
encode-level="LowercaseColorLevelEncoder"
stacktrace-key="stacktrace"
log-in-console=true

[minio]
access-key="UnNDmPdcfqFgQrcYbS1y"
access-secret="qDL9byiUG6teQLKg77qGmGjW8oMy5gjcAXmgm6P9"
endpoint="distsys-minio:9001" 
use-ssl=false 
bucket="distsys"
public-prefix="http://localhost:9001/distsys/"

[redis]
dsn="redis://:VVUH3PwskTzagyIlHTkx@distsys-redis:6379/0?protocol=3"
cluster-dsn=""

[casbin]
user-group-ptype="g"
resource-group-ptype="g2"
user-prefix="uid::"
user-group-prefix="group::"
resource-group-prefix="module::"
group-default-param="_"

[jwt]
exclude-paths=["/api/v1/user/login", "/api/v1/user/register", "/api/v1/user/refresh"]
access-key="yge0vugnbc1vrdp65excwh42izw7z9fa"
refresh-key="iew4w7cjfy0gy8qp6o1v65jxzar8nxp1"
access-expired-minutes=180
refresh-expired-minutes=200





